spring.application.name=projeto_programacao
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/projeto_programacao
spring.datasource.username=root
spring.datasource.password=pedro2006

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true